<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX6MZTAz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX6MZTAz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX6MZTAz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX6MZTAz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX6MZTAz\App_KernelDevDebugContainer([
    'container.build_hash' => 'X6MZTAz',
    'container.build_id' => '2dd90f4f',
    'container.build_time' => 1678974067,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX6MZTAz');
